name: Verify Gateway Service

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "gateway-service/**"

jobs:
  build:
    name: Verify Gateway Service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        run: ./gradlew :gateway-service:build

